apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: all-apps
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/leolee-rac/shieldapp.git
    targetRevision: feature/remove-kustomize
    path: appsets
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true