---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shieldappmq-deployment
  annotations:
    codefresh.io/app: simple-go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-app
  template:
    metadata:
      labels:
        app: hello-world-app
    spec:
      containers:
      - name: webserver-simple
        imagePullPolicy: Always
        image: docker.io/hello-world:linux
        ports:
        - containerPort: 8080
