---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Values.name }}-deployment'
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
    spec:
      containers:
      - name: {{ .Values.container.name }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
        ports:
        - containerPort: {{ .Values.container.port }}
