---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shieldappmq-deployment
  annotations:
    codefresh.io/app: simple-go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shield-mq
  template:
    metadata:
      labels:
        app: shield-mq
    spec:
      # nodeSelector:
      #   agentpool: infra
      containers:
        - name: shield-mq
          imagePullPolicy: Always
          image: shield-test-rhel:lastest
          ports:
            - containerPort: 80
