apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shields
  namespace: shield
spec:
  project: default
  source:
    repoURL: https://github.com/leolee-rac/shieldapp.git
    targetRevision: HEAD
    path: appsets
  destination:
    server: https://kubernetes.default.svc
    namespace: shield
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true