---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shieldapp-deployment
spec:
  template:
    spec:
      containers:
        - name: shield-app
          env:
            - name: ENV
              value: "prd"
            - name: GPU_ENABLED
              value: "1"
