---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shieldapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shield-app
  template:
    metadata:
      labels:
        app: shield-app
    spec:
      # nodeSelector:
      #   agentpool: infra
      containers:
      - name: shield-app
        imagePullPolicy: Never
        image: shield-test-rhel:latest
        ports:
          - containerPort: 9990
          - containerPort: 9001
