apiVersion: v1
kind: Service
metadata:
  name: shieldapp-service
spec:
  type: ClusterIP
  selector:
    app: shield-app
  ports:
    - name: management
      protocol: TCP
      port: 9990
      targetPort: 9990
    - name: http
      protocol: TCP
      port: 9001
      targetPort: 9001
