---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shieldapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shield-api
  template:
    metadata:
      labels:
        app: shield-api
    spec:
      # nodeSelector:
      #   agentpool: infra
      containers:
        - name: shield-api
          imagePullPolicy: Always
          image: shield-test-rhel:lastest
          ports:
            - containerPort: 9990
            - containerPort: 9001