---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shieldapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shield-api
  template:
    metadata:
      labels:
        app: shield-api
    spec:
      containers:
      - name: webserver-simple
        imagePullPolicy: Always
        image: docker.io/docker/example-voting-app-vote:latest
        ports:
        - containerPort: 80
