---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shieldappmq-deployment
  namespace: prd
spec:
  template:
    spec:
      containers:
        - name: webserver-simple
          env:
            - name: ENV
              value: "prd"
            - name: GPU_ENABLED
              value: "1"
