---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Values.name }}-deployment'
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
    spec:
      containers:
      - name: {{ .Values.container.name }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
        ports:
        - containerPort: {{ .Values.container.port }}

apiVersion: v1
kind: Service
metadata:
  name: '{{ .Values.name }}-service'
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.app }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}