---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shieldapp-deployment
spec:
  template:
    spec:
      containers:
        - name: shield-app
          env:
            - name: Environment
              value: "dev"
            - name: EnvironmentName
              value: "shielddev1"