---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shieldapp-deployment
  namespace: dev
spec:
  template:
    spec:
      containers:
        - name: webserver-simple
          env:
            - name: ENV
              value: "dev"
            - name: GPU_ENABLED
              value: "1"
