---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shieldapp-deployment
spec:
  template:
    spec:
      containers:
        - name: shield-app
          env:
            - name: SqlConnectionString
              value: "jdbc:sqlserver://192.168.1.68:1433;DatabaseName=shielddev1;user=sa;password=StrongP@ssword"
