---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shieldapp-deployment
spec:
  template:
    spec:
      containers:
        - name: shield-app
          env:
            - name: SqlConnectionString
              valueFrom:
                configMapKeyRef:
                  name: app-settings
                  key: SqlConnectionString
              #value: "jdbc:sqlserver://dcc-shdsql-d010.rac.com.au:1433;DatabaseName=shielddev2;user=sa;password=YourNewStrongP@ssword1"
