name: shieldapp
replicas: 1
app: trivial-go-web-app

container:
  name: webserver-simple
  image: docker.io/kostiscodefresh/simple-env-app
  tag: "1.0"
  imagePullPolicy: Always
  port: 8080

service:
  type: ClusterIP
  port: 80

spec:
  template:
    spec:
      containers:
      - name: webserver-simple
        env:
        - name: ENV
          value: "dev"
        - name: GPU_ENABLED
          value: "1"
        - name: UI_THEME
          value: "dark"
        - name: CACHE_SIZE
          value: "1024kb"
        - name: PAGE_LIMIT
          value: "25"
        - name: SORTING
          value: "ascending"
        - name: N_BUCKETS
          value: "42"